name: withergames
version: ${version}
main: dev.zxdzero.withergames.withergames
authors: [Puzzle_Dude98]
api-version: '1.21'
depend: [Vault, ZxdzeroEvents, MinecraftSession]
commands:
  tip:
    description: Tips your arrows (if you are at 75% worthiness)
  hearts:
    usage: /hearts [add|remove|reset] <amount> [player]
    description: Adds or removes hearts from a player
    permission: withergames.command.hearts
  items:
    usage: /items
    permission: withergames.command.items